import TextPage from '@/components/TextPage';

export default function Terms() {
    return (
        <TextPage
            title="Terms of Service"
            description="Last updated: January 2026"
        >
            <p>
                By using GapGens, you agree to these terms. Please read them carefully.
            </p>

            <h2>1. Usage Rights</h2>
            <p>
                You grant us a limited license to process your content solely for the purpose of providing our services to you. You retain all ownership rights to your original content and the derivatives generated by GapGens.
            </p>

            <h2>2. Acceptable Use</h2>
            <p>
                You agree not to use GapGens to generate content that is illegal, hateful, or abusive. You represent that you have the necessary rights (copyright) to the content you upload for analysis.
            </p>

            <h2>3. Disclaimer of Warranties</h2>
            <p>
                GapGens is provided "as is." AI is a rapidly evolving technology. While we strive for accuracy (avoiding hallucinations), we cannot guarantee 100% perfection. You are responsible for reviewing all generated content before publishing.
            </p>

            <h2>4. Liability Limitation</h2>
            <p>
                To the fullest extent permitted by law, GapGens shall not be liable for any indirect, incidental, or consequential damages resulting from your use of the service.
            </p>

            <h2>5. Changes to Terms</h2>
            <p>
                We may update these terms occasionally. If we make significant changes, we will notify you via email or a prominent notice on the dashboard.
            </p>
        </TextPage>
    );
}
